### ISSUE TITLE
Correcciones y sugerencias

### ISSUE THREAD

**Issue by flbulgarelli** [ciromartin/dds-2021#1]
¡Buenas!

Te dejo nuestros comentarios para esta entrega: 

1. Este constructor... https://github.com/ciromartin/dds-2021/blob/0fd678eb34ca895e6261ac51d3fcb4593b85d198/src/main/java/ar/edu/utn/frba/dds/qmp/dominio/Prenda.java#L9-L14 ... es un buen lugar para aplicar el principio de fail fast e introducir validaciones de presencia (por ejemplo usando Objects.notNull) dado que es algo en que se hace cierto hincapié en el enunciado al decir que las prendas deben ser válidas y que tenés un color obligatorio y otro secundario opcional.
2. Tu clase `Material`... https://github.com/ciromartin/dds-2021/blob/0fd678eb34ca895e6261ac51d3fcb4593b85d198/src/main/java/ar/edu/utn/frba/dds/qmp/dominio/Material.java#L3-L13 ... así como está planteada no está aportando nada realmente, es sólo un objeto que envuelve a un string, pero no aporta comportamiento ni tampoco está contribuyente a normalizar (es decir, tener una única representación posible) los nombres de materiales. Por ese motivo acá sería mejor usar otro `enum` (uno sin comportamiento en este caso) o como un simple string, pero validando que esté siempre dentro de un conjunto de valores posibles. 
3. Más allá de eso, ¡buen trabajo!

**Comment by flbulgarelli** [comment]
Sobre esta consulta: 

> Teniamos la duda si implementarlo con la facilidad que nos da los enums en java, o si hacerlo de una forma más generica como tener una Clase en la que tiene las distintas combinaciones de Tipo de prendas y genericas, y se encargaba de crear una nueva combinacion validando con estas combinaciones validas/creadas previamente.

Ambas opciones son correctas, pero considero que fueron el camino correcto al aprovechar las características que les provee el lenguaje.

**Comment by ciromartin** [comment]
Perfecto los comentarios super claros, muchas gracias por el feedback
